### ISSUE TITLE
Export CsvParser class so that it can be extended

### ISSUE THREAD

**Issue by pkese** [mafintosh/csv-parser#152]
### Feature Proposal

The csv-parse file ends with exporting
```javascript
module.exports = (opts) => new CsvParser(opts)
```

This prohibits a user to access the CsvParser class and extend its functionality using inheritance.

I'd suggest to export the class as well:

```javascript
module.exports = (opts) => new CsvParser(opts)
module.exports.CsvParserClass = CsvParser
```

### Feature Use Case

This would allow people to override parser behaviour by inheriting and extending the class (e.g. override the `writeRow` method - related to #149).

**Comment by shellscape** [comment]
Novel idea, but a fork or transform stream is still more appropriate for this project. This isn't `postcss` where several mainstream variations and extensions on CSS exist with widespread adoption. In situations like that, extensibility makes sense. Since this project mainly operates on the premise of streams and output via streams, extending the `writeRow` method can be accomplished by manipulating the stream.

Apologies for closing after the first comment on this and #149, but it's just not something I'm willing to entertain at the moment.

**Comment by pkese** [comment]
No problem. Thanks.
