### ISSUE TITLE
Support async, await grammar

### ISSUE THREAD

**Issue by jopemachine** [mafintosh/csv-parser#182]
### Feature Proposal

How about supporting async, await grammar like below way?

Option objects may be forwarded if necessary.

### Feature Use Case

```js
const readCsv = async (csvFilePath) => {
  const csvResult = []
  return new Promise((resolve, reject) => {
    try {
      fs.createReadStream(csvFilePath)
        .pipe(csv())
        .on('data', (data) => csvResult.push(data))
        .on('end', () => {
          resolve(csvResult)
        })
    } catch (e) {
      reject(e)
    }
  })
}

...

const csvArr = await readCsv(csvFilePath)
```

**Comment by shellscape** [comment]
Thanks for the suggestion. There are a bazillion packages on npm for promisifying streams, and a ton of variations on that theme. I'd recommend searching npm for the solution that fits you. At the moment, I'm going to make the call to decline the request for this package due to the availability of stream/promise solutions on npm.

**Comment by TrySound** [comment]
We use [get-stream](https://github.com/sindresorhus/get-stream).

**Comment by jopemachine** [comment]
> We use [get-stream](https://github.com/sindresorhus/get-stream).

Thanks for letting me know!

it helps a lot :)
