### ISSUE TITLE
Last header field gets double-quoted (unexpected)

### ISSUE THREAD

**Issue by igal1c0de4n** [mafintosh/csv-parser#79]
Using 1.12.0 here, seeing a weird issue. If to project this problem on the sample:

```js
var csv = require('csv-parser')
var fs = require('fs')

fs.createReadStream('some-csv-file.csv')
  .pipe(csv())
  .on('data', function (data) {
    console.log('Name: %s Age: %s', data.NAME, data.AGE)
  })
```

if `AGE` is the last header field, it's not possible to access it via `data.AGE`, but it is possible to access it via `data['"AGE"']`. What's more interesting is that it happens only with the last header field. So, as a workaround it's possible to add a comma at the end of the header field (which adds a new, zero-length header field). This gets `data.AGE` (or `data['AGE']`) to return the expected value.

Anyone else seen this issue?

**Comment by Dastari** [comment]
I had a similar issue with the first  header field. The object returned ended up looking like this: 

` Row {
   ' ID': '',
   PHOTOS: '28',
   TOWN: '',
   MAP: '',
   AKA: '',
   SUBURB: '',
   ADDRESS: '',
   HERITAGE: '',
   NAME: '',
   DENOMINATION: '',
   CHECKED: '',
   CORRECTED: '',
   NOTES: '',
   LOCATION: '' }`

The issue was the original source CSV from excel was saved with a [Byte order Mark](https://en.wikipedia.org/wiki/Byte_order_mark) which added a character at the start of the file. I suspect your source file may have a non recognized line break character at the end of your header line (or may have Carriage Return and Line Break)

It may be worth opening it in notepad and re-saving it or trying setting the **raw: false** constructor option or trying **newLine: '\r\n'** 

Or just download TextEdit and open the file then re-save it using another encoding (which is what I ended up doing)

**Comment by jdevost** [comment]
I had the same issue with Byte order Mark. 
On a Mac, you can clean up your CSV files using this command in a terminal:
`sed $'s/\xEF\xBB\xBF//g' file.csv`

**Comment by nnaku** [comment]
> @igalicodean I'm unable to reproduce. If this is still an issue on your end, please do let us know.

That's what @jdevost said. 

It's not "last header", I think it's first, because there invisible "character" at the beginning of the file. If that file is encoded "UTF8 with BOM". And in that case why that header/key gets escaped!

**Comment by shellscape** [comment]
For reference from other folks, if you have this issue, or are dealing with files that contain a leading Byte Order Mark, please use see: https://github.com/sindresorhus/strip-bom-stream. 

```js
const fs = require('fs');

const csv = require('csv-parser');
const stripBom = require('strip-bom-stream');

fs.createReadStream('data.csv')
  .pipe(stripBomStream())
  .pipe(csv())
  ...
```
